/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pokemon;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author MARIAEDUARDACOSTABAT
 */
public class PokemonMochila extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePokemon
     */
    private DefaultListModel<String> Pokemon;
    private ListModel<String> listaPokemon;
    
    
    
    public PokemonMochila() {
        initComponents();
        
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionar = new javax.swing.JButton();
        btnVerPokemons = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PokemonsDisponiveis = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        mochilaPokemons = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdicionar.setText("Adicionar pokemon à mochila");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnVerPokemons.setText("Ver lista dos Pokemons");
        btnVerPokemons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPokemonsActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover Pokemon da mochila");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(PokemonsDisponiveis);

        jScrollPane2.setViewportView(mochilaPokemons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVerPokemons)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover))
                .addGap(0, 207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAdicionar)
                .addGap(18, 18, 18)
                .addComponent(btnVerPokemons)
                .addGap(18, 18, 18)
                .addComponent(btnRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        Component frame = null;
        if (mochilaPokemons.size() >= 6) {
        JOptionPane.showMessageDialog(frame, "Mochila cheia! Remova um Pokémon antes de adicionar.");
        return;
    }
        Pokemon selecionado = (Pokemon) JOptionPane.showInputDialog(
            frame, "Escolha um Pokémon:", "Adicionar Pokémon",
            JOptionPane.QUESTION_MESSAGE, null,
            pokemonsDisponiveis.toArray(), pokemonsDisponiveis.get(0));

    if (selecionado != null) {
        mochilaPokemons.add(selecionado);
        mochilaModel.addElement(selecionado);
    }
           
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
         if (mochilaPokemons.isEmpty()) {
        JOptionPane.showMessageDialog(frame, "Mochila vazia!");
        return;
    }

    Pokemon selecionado = listaPokemons.getSelectedValue();
    if (selecionado != null) {
        mochila.remove(selecionado);
        mochilaModel.removeElement(selecionado);
    } else {
        JOptionPane.showMessageDialog(frame, "Selecione um Pokémon para remover.");
    }
}
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnVerPokemonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPokemonsActionPerformed
       public class PokemonMochila { private final ArrayList<Pokemon> pokemonsDisponiveis = new ArrayList<>(); private ArrayList<Pokemon> mochila = new ArrayList<>(); private JFrame frame; private DefaultListModel<Pokemon> mochilaModel = new DefaultListModel<>(); private JList<Pokemon> mochilaList = new JList<>(mochilaModel);

        public PokemonMochilaApp() {
        pokemonsDisponiveis.add(new Pokemon("Pikachu", "Elétrico", 5));
        pokemonsDisponiveis.add(new Pokemon("Charmander", "Fogo", 5));
        pokemonsDisponiveis.add(new Pokemon("Bulbasaur", "Planta", 5));
        pokemonsDisponiveis.add(new Pokemon("Squirtle", "Água", 5));

    }//GEN-LAST:event_btnVerPokemonsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> PokemonsDisponiveis;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVerPokemons;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> mochilaPokemons;
    // End of variables declaration//GEN-END:variables
}
